version: "3.8"

services:
  vertocoind:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vertocoin-node
    restart: always
    ports:
      - "9333:9333" # P2P port
      - "9332:9332" # RPC port
    volumes:
      - vertocoin_data:/home/vertocoin/.vertocoin
      - ./vertocoin.conf:/home/vertocoin/.vertocoin/vertocoin.conf:ro
    networks:
      - peercoin_vertocoin-network
    depends_on:
      tor-proxy:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "vertocoin-cli",
          "-rpcuser=vertouser",
          "-rpcpassword=YoK5Euk2aXx5IqiWiux1jZ1I6THNXmxkdlPIkvEnRb4",
          "getblockchaininfo",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Tor hidden service for vertocoind P2P connections
  tor:
    image: goldy/tor-hidden-service:latest
    container_name: vertocoin-tor
    restart: always
    environment:
      # VertoCoin node hidden service - P2P port mapping
      - SERVICE1_TOR_SERVICE_HOSTS=80:vertocoind:9333
      - SERVICE1_TOR_SERVICE_VERSION=3
      - TOR_LOG_LEVEL=notice
    volumes:
      - tor-data:/var/lib/tor
    networks:
      - peercoin_vertocoin-network
    healthcheck:
      test: ["CMD", "test", "-f", "/var/lib/tor/hidden_service/hostname"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Tor SOCKS proxy for outbound connections
  tor-proxy:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: vertocoin-tor-proxy
    restart: always
    ports:
      - "127.0.0.1:9050:9050" # SOCKS proxy port (bind to localhost only)
      - "127.0.0.1:9051:9051" # Control port (optional)
    networks:
      - peercoin_vertocoin-network
    environment:
      - TOR_OPTS=--SocksPort 0.0.0.0:9050 --ControlPort 0.0.0.0:9051 --HashedControlPassword 16:872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C --Log notice stdout --DataDirectory /tmp/tor
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9050"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  explorer:
    image: amirulmus/vertomax-explore:latest
    container_name: vertocoin-explorer
    restart: always
    ports:
      - "3002:3002"
    environment:
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_PORT=3002
      - BTCEXP_BITCOIND_HOST=vertocoind
      - BTCEXP_BITCOIND_PORT=9332
      - BTCEXP_BITCOIND_USER=vertouser
      - BTCEXP_BITCOIND_PASS=YoK5Euk2aXx5IqiWiux1jZ1I6THNXmxkdlPIkvEnRb4
      - BTCEXP_COIN=VTO
      - BTCEXP_DISPLAY_CURRENCY=vto
      - BTCEXP_LOCAL_CURRENCY=USD
      - BTCEXP_PRIVACY_MODE=false
      - BTCEXP_NO_INMEMORY_RPC_CACHE=true
      - BTCEXP_RPC_ALLOWALL=true
      - BTCEXP_SECURE_SITE=true
      - BTCEXP_PRIVACY_MODE=true
      - BTCEXP_RATE_LIMIT_WINDOW_MINUTES=-1
    networks:
      - peercoin_vertocoin-network
    depends_on:
      - vertocoind

  # Optional: Vertocoin CLI service for easy interaction
  vertocoin-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vertocoin-cli
    restart: always
    profiles:
      - cli # Only start when explicitly requested
    depends_on:
      - vertocoind
    volumes:
      - vertocoin_data:/home/vertocoin/.vertocoin
    networks:
      - peercoin_vertocoin-network
    entrypoint:
      [
        "vertocoin-cli",
        "-datadir=/home/vertocoin/.vertocoin",
        "-conf=/home/vertocoin/.vertocoin/vertocoin.conf",
      ]
    command: ["--help"] # Default to showing help

  # Optional: Explorer/monitoring service
  # You can add a blockchain explorer here in the future

volumes:
  vertocoin_data:
    driver: local
  tor-data:
    driver: local

networks:
  peercoin_vertocoin-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/16
